-- Criar tabela questao se não existir
CREATE TABLE IF NOT EXISTS questao (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero integer NOT NULL DEFAULT 0,
    prova_id bigint NOT NULL,
    disciplina_id bigint NOT NULL,
    enunciado text NOT NULL,
    alternativas text[] NOT NULL,
    resposta_correta integer NOT NULL,
    comentario text,
    status text NOT NULL DEFAULT 'ativa',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT questao_pkey PRIMARY KEY (id),
    CONSTRAINT questao_prova_id_fkey FOREIGN KEY (prova_id) REFERENCES prova(id) ON DELETE CASCADE,
    CONSTRAINT questao_disciplina_id_fkey FOREIGN KEY (disciplina_id) REFERENCES disciplina(id) ON DELETE CASCADE,
    CONSTRAINT questao_status_check CHECK (status IN ('ativa', 'inativa', 'revisao'))
);

-- Adicionar índices
CREATE INDEX IF NOT EXISTS idx_questao_prova_id ON questao(prova_id);
CREATE INDEX IF NOT EXISTS idx_questao_disciplina_id ON questao(disciplina_id);
CREATE INDEX IF NOT EXISTS idx_questao_status ON questao(status);

-- Adicionar comentários
COMMENT ON TABLE questao IS 'Tabela de questões do banco de dados';
COMMENT ON COLUMN questao.id IS 'Identificador único da questão';
COMMENT ON COLUMN questao.numero IS 'Número da questão na prova';
COMMENT ON COLUMN questao.prova_id IS 'ID da prova a qual a questão pertence';
COMMENT ON COLUMN questao.disciplina_id IS 'ID da disciplina da questão';
COMMENT ON COLUMN questao.enunciado IS 'Texto da questão';
COMMENT ON COLUMN questao.alternativas IS 'Array com as alternativas da questão';
COMMENT ON COLUMN questao.resposta_correta IS 'Índice da alternativa correta';
COMMENT ON COLUMN questao.comentario IS 'Comentário explicativo da questão';
COMMENT ON COLUMN questao.status IS 'Status da questão: ativa, inativa ou em revisão'; 