-- Criar tabela de listas de exercícios
CREATE TABLE IF NOT EXISTS listas_exercicios (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo text NOT NULL,
    descricao text,
    usuario_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT listas_exercicios_pkey PRIMARY KEY (id)
);

-- Criar tabela de questões das listas
CREATE TABLE IF NOT EXISTS lista_exercicios_questoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lista_exercicios_id bigint NOT NULL,
    questao_id bigint NOT NULL,
    ordem integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT lista_exercicios_questoes_pkey PRIMARY KEY (id),
    CONSTRAINT lista_exercicios_questoes_lista_exercicios_id_fkey FOREIGN KEY (lista_exercicios_id) REFERENCES listas_exercicios(id) ON DELETE CASCADE,
    CONSTRAINT lista_exercicios_questoes_questao_id_fkey FOREIGN KEY (questao_id) REFERENCES questao(id) ON DELETE CASCADE
);

-- Criar índices
CREATE INDEX IF NOT EXISTS idx_listas_exercicios_usuario_id ON listas_exercicios(usuario_id);
CREATE INDEX IF NOT EXISTS idx_lista_exercicios_questoes_lista_id ON lista_exercicios_questoes(lista_exercicios_id);
CREATE INDEX IF NOT EXISTS idx_lista_exercicios_questoes_questao_id ON lista_exercicios_questoes(questao_id);
CREATE INDEX IF NOT EXISTS idx_lista_exercicios_questoes_ordem ON lista_exercicios_questoes(ordem);

-- Adicionar comentários
COMMENT ON TABLE listas_exercicios IS 'Tabela de listas de exercícios criadas pelos usuários';
COMMENT ON TABLE lista_exercicios_questoes IS 'Tabela de relacionamento entre listas e questões'; 